### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by CaledoniaProject** [EthTx/ethtx#165]
I got 500 error on this link: https://ethtx.info/rinkeby/0x6fa35c21d1c48cc67ed07ca3a175f57b51bc63fe303a77eb30094b97bf08b561/

**Comment by kchojn** [comment]
Hi, 
There is a problem with the provider. Rinkeby will be deprecated soon, so we are thinking to stop supporting it. 👀

**Comment by CaledoniaProject** [comment]
Understood.
