### ISSUE TITLE
ENS lookup bug

### ISSUE THREAD

**Issue by engn33r** [EthTx/ethtx#177]
I was comparing ethtx output to other similar tools and found a case where ethtx resolves an incorrect ENS address.

In ethtx.info, the offerer value is `babywhale.eth`. Clicking on babywhale.eth in ethtx uses the address 0x8af6e15ed513b5b73573f58158b1b0bbd5085ec7. But babywhale.eth on etherscan resolves to 0x9bf2eb61a3beb7afb1213029f3f1ae3e08ede755
https://ethtx.info/mainnet/0x665c4db0b7dcf44eb2ead3d455b12bfb244de9a2d3239d756ca3fbdbf21817bb/

Meanwhile, two other transaction explorers (which don't support ENS resolution) show the value 0x8af6e15ed513b5b73573f58158b1b0bbd5085ec7 for the offerer
https://phalcon.blocksec.com/tx/eth/0x665c4db0b7dcf44eb2ead3d455b12bfb244de9a2d3239d756ca3fbdbf21817bb
https://tx.eth.samczsun.com/ethereum/0x665c4db0b7dcf44eb2ead3d455b12bfb244de9a2d3239d756ca3fbdbf21817bb

0x8af6e15ed513b5b73573f58158b1b0bbd5085ec7 does hold two ENS addresses, but babywhale.eth is not one of them, so the wrong ENS address is getting displayed.

**Comment by kchojn** [comment]
Hi @engn33r,
Thanks for reporting the bug, indeed it was a web3 bug, fortunately, they are preparing for version 6, where this will be solved by default 🤝
Corrected version 0.3.20 coming soon
