### ISSUE TITLE
Cheap archived node

### ISSUE THREAD

**Issue by highoak** [EthTx/ethtx#18]
What is the cheapest solution for geth archive node with debug trace methods support?

**Comment by LogvinovLeon** [comment]
Hmm. If you want to just get access to the node - probably Alchemy is the cheapest. For 49$/month you get the access to debug tracing.

If you want to host your own node - you'll need  a lot of disk space and a beefy machine to sync the node. After that you can downgrade the instance, but you'll still need like 10T of SSD. If you can set a threshold like: No requests to transactions older than a year - they you can initially sync the node as non archive and only then switch it to being archive. That'll save you some disk space. 

You can also try your lock with erigon (ex: turbo-geth). It lakes much less disk space and syncs in an order of magnitude faster, but the question was about Geth.

**Comment by highoak** [comment]
Thank you
Does alchemy work for ethtx?
I read that they don't support debug_traceTransaction on mainnet
https://docs.alchemy.com/alchemy/documentation/apis/enhanced-apis/debug-api

**Comment by tmierzwa** [comment]
Yes, you re right, Alchemy does not do that.
We talked to them some time ago and the claimed they plan to do so, but without any specific dates.
This is why we host our own node for EthTx mainnet.
Probably we will provide another one for Goerli very soon.

**Comment by highoak** [comment]
I use quicknode.com archive node. It cost 250$/mo but it's partiry node
How hard is to support parity node I think the method name is quite different
trace_replayTransaction
https://openethereum.github.io/JSONRPC-trace-module#trace_replaytransaction

**Comment by tmierzwa** [comment]
Yes it is different and we do not support it anymore.
It's not only the method name but the whole logic of getting traces is completely different.
In fact the old version of EthTx used Parity, but we switched to Geth due to many limitations of it.

**Comment by highoak** [comment]
Do you use real server or virtual one?
What type and requirements?

**Comment by LogvinovLeon** [comment]
We're currently operating on AWS on `m5n.2xlarge`, but that's mostly for historical reasons and we're researching other instance types to switch. Running the node is mostly about disk and we can be ok with a smaller machine.

**Comment by 0xPlainview** [comment]
FYI, you can also use [archivenode](https://archivenode.io/) which is a free resource. The caveat being that It's for smaller projects and the rate limit is 10 requests/ second.
