### ISSUE TITLE
Account balances not adding up for Eth for USDT transaction on UniswapV3

### ISSUE THREAD

**Issue by lemiesz** [EthTx/ethtx#186]
So it seems that there is some bug with how multicalls are being handled. 

here https://etherscan.io/tx/0x093cdad6594e26543fdec775ddb99c6a761bace9512332a5aec50b38b39e92d9 

You see that I have received $126 USDT for .1 eth.  

However then the transaction is analyzed  it does not seem to reflect that: https://ethtx.info/mainnet/0x093cdad6594e26543fdec775ddb99c6a761bace9512332a5aec50b38b39e92d9/ 

Other tool seems to handle this better https://phalcon.blocksec.com/tx/eth/0x093cdad6594e26543fdec775ddb99c6a761bace9512332a5aec50b38b39e92d9. 

Anyone know if this is a bug... or am i just misinterpreting the result.

**Comment by tmierzwa** [comment]
This was a bug with USDT semantics which used incorrect decimal precision.
Should be fixed now. Please check...

**Comment by lemiesz** [comment]
I stil see this issue in ethtx link listed about. 

going to https://new.ethtx.info/mainnet/0x093cdad6594e26543fdec775ddb99c6a761bace9512332a5aec50b38b39e92d9 

I see that it just fails to load due to a null pointer exception in the NextJs render

**Comment by piotr-rudnik** [comment]
Hey, so we just deployed new version of ethtx and there is a change in this tx: https://ethtx.info/mainnet/0x093cdad6594e26543fdec775ddb99c6a761bace9512332a5aec50b38b39e92d9/ balances look better rn. If you could confirm this we can close this issue.

**Comment by lemiesz** [comment]
Beautiful thank you.
