### ISSUE TITLE
Binance chain support

### ISSUE THREAD

**Issue by highoak** [EthTx/ethtx#20]
Greate project. Thank you!
Do you have plans to support the Binance chain?

**Comment by tmierzwa** [comment]
Technically it's possible, we just need a fully synced archive node.
We are not actively working on it, but will look into this soon.

**Comment by wulasite** [comment]
well, I test it on bsc, but i don't why the code must use ens contract which not exist in bsc .  I have no choice to delete the ens code. 
I think it can be optional

**Comment by SergeC** [comment]
Any update on BSC? The Moralis can provide an archive node.
