### ISSUE TITLE
Inspecting tx but ran into '500 Unexpected Error'

### ISSUE THREAD

**Issue by NIC619** [EthTx/ethtx#31]
Hi, I have trouble inspecting my tx via ethtx. Is this the place to report tx that causes ethtx.info to keep returning '500 Unexpected Error'?

**Comment by piotr-rudnik** [comment]
Hey, thanks for opening new issue. For now we are inspecting every error manually, there is not that many transactions that fail in decoding. If you can, please provide tx hash and I will check what's wrong.

**Comment by NIC619** [comment]
Thanks a lot! Below are one of the example tx: https://etherscan.io/tx/0xe4d34656c0a5c758f4b8c41acbf418c178954e19e276e53d673a4e1281fb26dc

One of the contract in the call chain is `AMMWrapperWithPath` which has overloaded `swap` function and `Swapped` event. Wonder if it's the cause because other txs that go through another contract `AMMWrapper` which has no overloaded function or event work just fine with ethtx.

**Comment by piotr-rudnik** [comment]
Hey, thanks for answering. Have been looking through logs and problem there is a problem with semantics used for decoding and caching. We are working on the fix.

**Comment by piotr-rudnik** [comment]
Hey, we pushed some changes and tx can now decode without problems! Thanks again for raising this issue, will close this for now.

**Comment by MattAlp** [comment]
Another one: https://ethtx.info/mainnet/0x3c351cea655b8a50348e6ffa1bfff5b4ce68f99366cfad3d8a02ffb01f63138a/

**Comment by piotr-rudnik** [comment]
Hey, thanks for alerting us. Currently looks like our mainnet eth node is down, and since its Saturday, it might be a bit harder to bring right people to help. I'm checking out what we need to do right now.

**Comment by piotr-rudnik** [comment]
Hey again, looks like this tx is decoding fine now :+1:

**Comment by MattAlp** [comment]
Thanks!
