### ISSUE TITLE
Getting started script not working

### ISSUE THREAD

**Issue by 0x1355** [EthTx/ethtx#78]
Just discovered this repo. Really interested to test it out. 

However, when I tried to run the 'Getting started1' script in README, I came across a few errors:

### Error 1:
```  
File "test.py", line 6
    mongo_database = "mongomock://localhost"
    ^
SyntaxError: invalid syntax
```
I got passed this by adding commas before each inline comment. Then I got another error:

### Error 2:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    ethtx_config = EthTxConfig(
TypeError: __init__() got an unexpected keyword argument 'mongo_database'
```
I looked into `ethtx.py` and didn't see any `mongo_database` attribute. So I commented the `mongo_database` line out. Then I got another error:

### Error 3:
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    ethtx = EthTx.initialize(ethtx_config)
  File "/home/lsa/anaconda3/lib/python3.8/site-packages/ethtx/ethtx.py", line 122, in initialize
    repository = MongoSemanticsDatabase(db=mongo_client.get_database())
  File "/home/lsa/anaconda3/lib/python3.8/site-packages/mongomock/mongo_client.py", line 133, in get_database
    db = self.get_default_database(
  File "/home/lsa/anaconda3/lib/python3.8/site-packages/mongomock/mongo_client.py", line 151, in get_default_database
    raise ConfigurationError('No default database name defined or provided.')
pymongo.errors.ConfigurationError: No default database name defined or provided.
```

Can you advise if I am doing something incorrectly? Thanks.

**Comment by 0x1355** [comment]
My modified `Getting started` script. 
```python
from ethtx import EthTx, EthTxConfig
from ethtx.models.decoded_model import DecodedTransaction

ethtx_config = EthTxConfig(
    mongo_connection_string="mongomock://localhost",  ##MongoDB connection string,
#    mongo_database = "mongomock://localhost",  ##MongoDB database,
    etherscan_api_key = "xxxxx",  ##Etherscan API key,
    web3nodes = {
                "mainnet": {
                    "hook": "xxxxx", # multiple nodes supported, separate them with comma
                    "poa": False  # represented by bool value
                }
            },
            default_chain = "mainnet",
            etherscan_urls = {"mainnet": "https://api.etherscan.io/api",},
)

ethtx = EthTx.initialize(ethtx_config)
transaction: DecodedTransaction = ethtx.decoders.decode_transaction(
    '0x50051e0a6f216ab9484c2080001c7e12d5138250acee1f4b7c725b8fb6bb922d')
```

**Comment by piotr-rudnik** [comment]
Hey, thanks for reporting this. Our readme files are not updated too often since project is still rapidly evolving and APIs are changing. Definitely this needs to be corrected. Will push some fixes soon.

**Comment by kchojn** [comment]
Additionally - version 0.3.4 will include many fixes,  so as Piotrek said, there will be also added fixes to the documentation. 

### Error 3 Fix:
We moved the default database to the connection string, so you can fix if by adding `ethtx` (for example) database to string: `mongomock://localhost/ethtx`

**Comment by piotr-rudnik** [comment]
Ok so we fixes those problems in readme and tested this example code, looks like it's working, so I will close this issue. If you have any more problems, please fell free to reach out to us. Thanks again for reporting this issue!

**Comment by 0x1355** [comment]
Thanks guys. You are FAST!
