### ISSUE TITLE
from_address is none

### ISSUE THREAD

**Issue by wulasite** [EthTx/ethtx#89]
When I run get start script,I get error:
Traceback (most recent call last):
  File "Code/python/Blockchain/eth_trans_decode.py", line 23, in <module>
    transaction: DecodedTransaction = ethtx.decoders.decode_transaction(
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/ethtx/ethtx.py", line 67, in decode_transaction
    return self._decoder_service.decode_transaction(chain_id, tx_hash)
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/ethtx/decoders/decoder_service.py", line 47, in decode_transaction
    transaction = self.web3provider.get_full_transaction(
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/ethtx/providers/web3_provider.py", line 466, in get_full_transaction
    w3calltree = self.get_calls(tx_hash, chain_id)
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/ethtx/providers/web3_provider.py", line 255, in get_calls
    return self._create_call_from_debug_trace_tx(
  File "/opt/anaconda3/envs/py3.8/lib/python3.8/site-packages/ethtx/providers/web3_provider.py", line 490, in _create_call_from_debug_trace_tx
    main_parent = W3CallTree(tx_hash=tx_hash, chain_id=chain_id, **w3input)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for W3CallTree
type
  field required (type=value_error.missing)
from_address
  none is not an allowed value (type=type_error.none.not_allowed)

When debug, I found from_address is set to none in ethtx/providers/web3_provider.py , 479 line. 

I have no idea why?  And I print the debug_transaction response , it dose not contain from_address , either.

**Comment by damiandennis** [comment]
I had this same issue originally when using a hardhat fork from mainnet, are you possibly doing that? I did not resolve the issue just went on to using alchemy with polygon instead as I had trouble running a node (always get close but then I run out of some sort of capacity RAM or HDD space) but even then ran into a few issues with rate limiting and ens which is not on polygon but got it working in the end with the pull request I have submitted.

**Comment by piotr-rudnik** [comment]
Could you provide more debug information for this issue? Info about which chain do you use, tx hash and node type should be sufficient for now. We are using pydantic to make sure data in models is in correct types, and this validation is causing the problem. For a quick fix, you could try making this field optional by changing fields type in file `ethtx/models/w3_model.py` in class 'W3CallTree' from `str` to `Optional[str]`
From this:
```
class W3CallTree(BaseModel):
    ...
    from_address: str
```
to this:
```
class W3CallTree(BaseModel):
    ...
    from_address: Optional[str]
```
and change `to_object` method from this:
```
    def to_object(self) -> Call:
        from_address = self.from_address
```
to this:
```
    def to_object(self) -> Call:
        from_address = self.from_address if self.from_address else "" ""
```

 but I can't guarantee this will work, but it's worth a shot if you really need this tx decoded. I can't really make a PR with this without testing and making sure it's a valid solution, so again, if you could get me more info about transaction you are trying to decode and/or results of this hacked fix, we could work out something better.

**Comment by enmohsinali** [comment]
Can someone please tell me how many requests per decode sent to a full archive node ?

**Comment by piotr-rudnik** [comment]
@enmohsinali  It's a bit of out the line from original question, but it could be from 1 to multiple hundreds of requests depending on transaction and how complicated it is.

**Comment by enmohsinali** [comment]
Sorry I couldn't find a better place for the question.
If there is any discord related to this repo please mention it.
By they way thanks alot.

**Comment by kchojn** [comment]
> Sorry I couldn't find a better place for the question.
> 
> If there is any discord related to this repo please mention it.
> 
> By they way thanks alot.

Hey, we have Discord. You can find a link to it on our website, in the footer: https://tokenflow.live/

**Comment by wulasite** [comment]
I think the problem is my request node is not a full archive node.

**Comment by wulasite** [comment]
by the way, I think the ens function can be optional , it is not work on bsc

**Comment by enmohsinali** [comment]
@kchojn Yeah Found it now.
Thanks

**Comment by kchojn** [comment]
@wulasite, we was thinking about optional ens and we will implement this in the future releases, for sure. Thanks for the idea!
